# Generated by Django 5.1 on 2025-05-11 16:12

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionType',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='MS')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kiểu kết nối')),
            ],
            options={
                'verbose_name': 'Kiểu cáp kết nối',
                'verbose_name_plural': 'Kiểu cáp kết nối',
                'db_table': 'connectiontype',
            },
        ),
        migrations.CreateModel(
            name='DocumentTypes',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='MS')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Loại văn bản')),
            ],
            options={
                'verbose_name': 'Loại văn bản',
                'verbose_name_plural': 'Loại văn bản',
                'db_table': 'document_types',
            },
        ),
        migrations.CreateModel(
            name='ErrorType',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='MS')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Hỏng hóc')),
            ],
            options={
                'verbose_name': 'Hỏng hóc',
                'verbose_name_plural': 'Hỏng hóc',
                'db_table': 'errortype',
            },
        ),
        migrations.CreateModel(
            name='HandleStatusType',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='MS')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Trạng thái')),
            ],
            options={
                'verbose_name': 'Trạng thái xử lý',
                'verbose_name_plural': 'Trạng thái xử lý',
                'db_table': 'handlestatustype',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='MS')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Hãng sản xuất')),
            ],
            options={
                'verbose_name': 'Hãng sản xuất',
                'verbose_name_plural': 'Hãng sản xuất',
                'db_table': 'manufacturer',
            },
        ),
        migrations.CreateModel(
            name='NetworkAddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Ms')),
                ('mac_address', models.CharField(default='FF:FF:FF:FF:FF:FF', max_length=17, unique=True, verbose_name='Địa chỉ MAC')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Địa chỉ IP')),
            ],
            options={
                'verbose_name': 'Địa chỉ mạng',
                'verbose_name_plural': 'Địa chỉ mạng',
                'db_table': 'networkaddress',
            },
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='MS')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Chức vụ')),
            ],
            options={
                'verbose_name': 'Chức vụ',
                'verbose_name_plural': 'Chức vụ',
                'db_table': 'staffrole',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='MS')),
                ('name', models.CharField(max_length=100, verbose_name='Tên Phòng/Ban')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='common.department', verbose_name='Phòng/Ban cha')),
            ],
            options={
                'verbose_name': 'Phòng/Ban',
                'verbose_name_plural': 'Phòng/Ban',
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='MS')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Loại trang bị')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='common.equipmenttype', verbose_name='Loại trang bị cha')),
            ],
            options={
                'verbose_name': 'Loại trang bị',
                'verbose_name_plural': 'Loại trang bị',
                'db_table': 'equipment_type',
            },
        ),
        migrations.CreateModel(
            name='EquipmentModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='MS')),
                ('name', models.CharField(max_length=200, verbose_name='Trang bị')),
                ('battery', models.BooleanField(default=False, verbose_name='Tích hợp pin sạc')),
                ('needdriver', models.BooleanField(default=False, verbose_name='Cần driver riêng')),
                ('features', models.TextField(blank=True, null=True, verbose_name='Tính năng trang bị')),
                ('specifications', models.JSONField(blank=True, default=dict, null=True, verbose_name='Thông số kỹ thuật')),
                ('cable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.connectiontype', verbose_name='Kiểu kết nối')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.equipmenttype', verbose_name='Loại trang bị')),
            ],
            options={
                'verbose_name': 'Model trang bị',
                'verbose_name_plural': 'Model trang bị',
                'db_table': 'equipmentmodel',
            },
        ),
        migrations.CreateModel(
            name='RequirementType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='MS')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên yêu cầu')),
                ('unit', models.CharField(max_length=100, verbose_name='Đơn vị tính')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='common.requirementtype', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Loại Yêu cầu XLKT',
                'verbose_name_plural': 'Loại yêu cầu XLKT',
                'db_table': 'requirementtype',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='MS')),
                ('name', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('status', models.BooleanField(default=False, verbose_name='Đã nghỉ việc')),
                ('phonenumber', models.CharField(blank=True, max_length=10, null=True, verbose_name='Số điện thoại')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='common.department', verbose_name='Phòng/Ban')),
                ('staffrole', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.staffrole', verbose_name='Chức vụ')),
            ],
            options={
                'verbose_name': 'Cán bộ/Nhân viên',
                'verbose_name_plural': 'Cán bộ/Nhân viên',
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='StaffUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accounts', to='common.staff', verbose_name='Nhân viên')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_user', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Tài khoản',
                'verbose_name_plural': 'Tài khoản',
                'db_table': 'staff_user',
                'unique_together': {('user', 'staff')},
            },
        ),
    ]
