# Generated by Django 5.1 on 2025-05-11 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingDocuments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('ms', models.CharField(max_length=20, verbose_name='Số văn bản')),
                ('date', models.DateField(verbose_name='Ngày')),
                ('title', models.CharField(max_length=2000, verbose_name='Trích yếu')),
                ('quantity', models.IntegerField(verbose_name='Số lượng bản')),
                ('pages', models.IntegerField(verbose_name='Số lượng tờ')),
                ('security', models.CharField(blank=True, choices=[('BT', 'Thường'), ('MM', 'Mật'), ('TT', 'Tối mật'), ('TTT', 'Tuyệt mật')], default='BT', max_length=20, null=True, verbose_name='Độ mật')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.documenttypes', verbose_name='Loại văn bản')),
                ('sender', models.ManyToManyField(blank=True, related_name='docs_sender', to='common.staff', verbose_name='Người gửi')),
                ('source', models.ManyToManyField(blank=True, related_name='docs_source', to='common.department', verbose_name='Cơ quan gửi')),
            ],
            options={
                'verbose_name': 'Quản lý văn bản đến',
                'verbose_name_plural': 'Văn bản đến',
                'db_table': 'incoming_documents',
            },
        ),
        migrations.CreateModel(
            name='OutgoingDocuments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('ms', models.CharField(max_length=20, verbose_name='Số văn bản')),
                ('date', models.DateField(verbose_name='Ngày')),
                ('title', models.CharField(max_length=2000, verbose_name='Trích yếu')),
                ('quantity', models.IntegerField(verbose_name='Số lượng bản')),
                ('pages', models.IntegerField(verbose_name='Số lượng tờ')),
                ('security', models.CharField(blank=True, choices=[('BT', 'Thường'), ('MM', 'Mật'), ('TT', 'Tối mật'), ('TTT', 'Tuyệt mật')], default='BT', max_length=20, null=True, verbose_name='Độ mật')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('destination', models.ManyToManyField(blank=True, related_name='docs_destination', to='common.department', verbose_name='Cơ quan nhận')),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.documenttypes', verbose_name='Loại văn bản')),
                ('receiver', models.ManyToManyField(blank=True, related_name='docs_receiver', to='common.staff', verbose_name='Người nhận')),
            ],
            options={
                'verbose_name': 'Quản lý văn bản đi',
                'verbose_name_plural': 'Văn bản đi',
                'db_table': 'outgoing_documents',
            },
        ),
    ]
