# Generated by Django 5.1 on 2025-05-11 16:12

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('serial', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Số seri trang thiết bị')),
                ('ms', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='MS')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Năm đưa vào sử dụng')),
                ('source', models.CharField(blank=True, choices=[('NS', 'Ngân sách'), ('DA', 'Dự án'), ('KH', 'Khác')], max_length=10, null=True, verbose_name='Nguồn cấp trang bị KTĐB')),
                ('specification', models.TextField(blank=True, null=True, verbose_name='Cấu hình trang bị')),
                ('storage_location', models.TextField(blank=True, null=True, verbose_name='Vị trí lưu trữ trang bị')),
                ('country', models.CharField(blank=True, choices=[('VN', 'Việt Nam'), ('US', 'United States'), ('FR', 'France'), ('JP', 'Japan'), ('CN', 'China')], max_length=3, null=True, verbose_name='Xuất xứ')),
                ('purpose', models.CharField(blank=True, choices=[('GD', 'Giao dịch'), ('PTDL', 'Phân tích dữ liệu'), ('QLRR', 'Quản lý rủi ro'), ('KT', 'Kế toán')], max_length=100, null=True, verbose_name='Mục đích sử dụng')),
                ('group', models.CharField(blank=True, choices=[('1', 'Trang thiết bị'), ('2', 'Vật tư, phụ tùng thay thế')], max_length=100, null=True, verbose_name='Nhóm')),
                ('available', models.BooleanField(default=True, verbose_name='Sẵn sàng đưa vào sử dụng')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Ngày hết hạn bảo hành')),
                ('waranty_info', models.TextField(blank=True, null=True, verbose_name='Thông tin bảo hành')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.department', verbose_name='Phòng/ban quản lý')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.manufacturer', verbose_name='Hãng sản xuất')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.equipmentmodel', verbose_name='Model trang thiết bị')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='equipments.equipment', verbose_name='Thiết bị cha')),
            ],
            options={
                'verbose_name': 'Trang thiết bị',
                'verbose_name_plural': 'Trang thiết bị',
                'db_table': 'equipment',
            },
        ),
        migrations.CreateModel(
            name='ConsumableEquipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Số lượng')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.equipment', verbose_name='Trang bị')),
            ],
            options={
                'verbose_name': 'Vật tư tiêu hao',
                'verbose_name_plural': 'Vật tư tiêu hao',
                'db_table': 'consumable_equipment',
            },
        ),
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ms')),
                ('network', models.CharField(blank=True, choices=[('intranet', 'Mạng nội bộ'), ('internet', 'Internet'), ('dmz', 'DMZ (Vùng phi quân sự)'), ('vpn', 'VPN (Mạng riêng ảo)')], max_length=50, null=True, verbose_name='Mạng máy tính')),
                ('address', models.ManyToManyField(blank=True, related_name='network_device_address', to='common.networkaddress', verbose_name='Địa chỉ mạng')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_devices', to='equipments.equipment', verbose_name='Thiết bị')),
            ],
            options={
                'verbose_name': 'Thiết bị mạng',
                'verbose_name_plural': 'Thiết bị mạng',
                'db_table': 'network_devices',
            },
        ),
    ]
