"""
Django settings for qlkt project.

Generated by 'django-admin startproject' using Django 3.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ifu^h&d+1g)cnvk!@j0sm$&n%x=@ru$w89u90*hzs^v22!13u9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS_ENV = os.environ.get("ALLOWED_HOSTS", "")
ALLOWED_HOSTS = [h for h in ALLOWED_HOSTS_ENV.split(",") if h] or ["localhost", "127.0.0.1"]

# CSRF trusted origins for reverse proxy / custom ports (override with CSRF_TRUSTED_ORIGINS env)
CSRF_TRUSTED_ORIGINS_ENV = os.environ.get("CSRF_TRUSTED_ORIGINS", "")
DEFAULT_CSRF_ORIGINS = [
    "http://localhost:8080",
    "http://127.0.0.1:8080",
]
CSRF_TRUSTED_ORIGINS = [o for o in CSRF_TRUSTED_ORIGINS_ENV.split(",") if o] or DEFAULT_CSRF_ORIGINS


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'chartjs',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'smart_selects',
    'import_export',
    'rangefilter',
    'mptt',
    'equipments.apps.EquipmentsConfig',
    'common.apps.CommonConfig',
    'documents.apps.DocumentsConfig',
    'operations.apps.OperationsConfig',
    'django_mptt_admin',
    'nested_admin',
]
USE_DJANGO_JQUERY = True  # Use Django's jQuery (or False to use the one that comes with smart_selects)
JAZZMIN_SETTINGS = {
    "site_title": "QLTBKT",
    "site_header": "Hệ thống quản lý trang bị kỹ thuật",
    "site_brand": "QLTBKT",
    # "site_icon": "images/logo.png",
    # Add your own branding here
    # "site_logo": "images/logo.png",
    "welcome_sign": "Hệ thống quản lý trang bị kỹ thuật",
    # Copyright on the footer
    "copyright": "anhttb",
    "user_avatar": None,
    ############
    # Top Menu #
    ############
    # Links to put along the top menu
    "topmenu_links": [
        # {"name": "Trang chủ", "url": "admin:index", "permissions": ["auth.view_user"]},
        # {"name": "Thống kê & báo cáo", "url": "/equipment-stats/", "icon": "fas fa-chart-bar", "permissions": ["auth.view_user"]},
        {"model": "auth.User"},
        {"model": "auth.Group"},
    ],
    
    #############
    # Side Menu #
    #############
    # Whether to display the side menu
    "hide_apps": ["auth",],
    # "hide_models": ["common.StaffRank", "common.StaffRole", "common.UsagePurpose", "common.HandleStatusType", "common.Manufacturer", "common.ConnectionType", "common.ComputerNetwork"],  # Hoặc có thể ẩn riêng từng model bằng ["auth.user", "auth.group"]
    "show_sidebar": True,
    # List of apps (and/or models) to base side menu ordering off of (does not need to contain all apps/models)
    "order_with_respect_to": [
        "equipments",
        "equipments.Equipment",
        "equipments.ConsumableEquipment",
        "equipments.NetworkDevice",
        "operations",
        "operations.Requirement",
        "operations.EquipmentRepair",
        "operations.EquipmentHandover",
        "operations.EquipmentLiquidation",
        "operations.EquipmentDeployment",
        "operations.NetworkMaintenanceLog",
        "documents",
        "common",
        "common.Department",
        "common.Staff",
        "common.StaffRank",
        "common.StaffRole",
        "common.DocumentTypes",
        "common.RequirementType",
        "common.EquipmentType",
        "common.EquipmentModel",
        "common.UsagePurpose",
        "common.HandleStatusType",
        "common.ConnectionType",
        "common.Manufacturer",
        "common.NetworkAddress",
        "common.ComputerNetwork",
        
        
    ],
    # Whether to aut expand the menu
    "navigation_expanded": True,
    # Custom icons for side menu apps/models See https://fontawesome.com/icons?d=gallery&m=free&v=5.0.0,5.0.1,5.0.10,5.0.11,5.0.12,5.0.13,5.0.2,5.0.3,5.0.4,5.0.5,5.0.6,5.0.7,5.0.8,5.0.9,5.1.0,5.1.1,5.2.0,5.3.0,5.3.1,5.4.0,5.4.1,5.4.2,5.13.0,5.12.0,5.11.2,5.11.1,5.10.0,5.9.0,5.8.2,5.8.1,5.7.2,5.7.1,5.7.0,5.6.3,5.5.0,5.4.2
    # for the full list of 5.13.0 free icon classes
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "users.User": "fas fa-user",
        "auth.Group": "fas fa-users",
        "admin.LogEntry": "fas fa-file",

        "equipments.Equipment": "fas fa-laptop",
        "equipments.ConsumableEquipment": "fas fa-boxes",
        "equipments.NetworkDevice": "fas fa-server",

        "documents.OutgoingDocuments": "fas fa-file-export",
        "documents.IncomingDocuments": "fas fa-file-import",

        "operations.Requirement": "fas fa-file-signature",
        "operations.NetworkMaintenanceLog": "fas fa-tools",
        "operations.EquipmentRepair": "fas fa-screwdriver-wrench",
        "operations.EquipmentHandover": "fas fa-hand-holding-hand",
        "operations.EquipmentLiquidation": "fas fa-trash-can-arrow-up",
        "operations.EquipmentDeployment": "fas fa-business-time",

        "common.ComputerNetwork": "fas fa-network-wired",
        "common.NetworkAddress": "fas fa-sitemap",
        "common.EquipmentType": "fas fa-laptop-code",
        "common.EquipmentModel": "fas fa-computer",
        "common.Staff": "fas fa-user-tie",
        "common.StaffRank": "fas fa-ranking-star",
        "common.StaffRole": "fas fa-clipboard-user",
        "common.Department": "fas fa-building",
        "common.DocumentTypes": "fas fa-file",
        "common.UsagePurpose": "fas fa-bullseye",
        "common.HandleStatusType": "fas fa-file",
        "common.BaseDocument": "fas fa-file",
        "common.StaffUser": "fas fa-user-tie",
        "common.ConnectionType": "fas fa-plug",
        "common.Manufacturer": "fas fa-industry",
        "common.RequirementType": "fas fa-file-signature",
        "common.HandleStatusType": "fas fa-spinner",

    },
    # # Icons that are used when one is not manually specified
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-arrow-circle-right",
    #################
    # Related Modal #
    #################
    # Use modals instead of popups
    "related_modal_active": False,
    #############
    # UI Tweaks #
    #############
    # Relative paths to custom CSS/JS scripts (must be present in static files)
    # Uncomment this line once you create the bootstrap-dark.css file
    "custom_css": "css/custom_admin.css",
    "custom_js": None,
    
    "use_google_fonts_cdn": False,
    # Whether to show the UI customizer on the sidebar
    "show_ui_builder": True,
    ###############
    # Change view #
    ###############
    "changeform_format": "horizontal_tabs",
    # override change forms on a per modeladmin basis
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
        # "equipments.Equipment": "vertical_tabs",
    },
    # Add a language dropdown into the admin
    "language_chooser": True,
    # "custom_links": {
    #     "equipments": [{
    #         "name": "Thống kê thiết bị",
    #         "url": "/equipment-stats/",
    #         "icon": "fas fa-chart-bar",  # icon FontAwesome
    #         "permissions": ["equipments.view_model"],
    #     }]
    # },
}
JAZZMIN_UI_TWEAKS = {
    "theme": "cosmo",
}

COUNTRIES = [
    ('VN', 'Việt Nam'),
    ('US', 'United States'),
    ('FR', 'France'),
    ('JP', 'Japan'),
    ('CN', 'China')
    # ... thêm tùy ý
]

SOURCES = [
    ('NS', 'Ngân sách'),
    ('DA', 'Dự án'),
    ('KH', 'Khác'),
    # ... thêm tùy ý
]

GROUPS = [
    ('1', 'Trang thiết bị'),
    ('2', 'Vật tư, phụ tùng thay thế'),
]

REQUIREMENT_STATUSES = [
    ('MOI', 'Mới tạo (chờ trưởng phòng duyệt)'),
    ('TPC', 'Trưởng phòng đã duyệt (chờ trưởng phòng IT)'),
    ('TPD', 'Trưởng phòng IT đã duyệt (chờ phân công)'),
    ('DPC', 'Đã phân công (đang xử lý)'),
    ('DXL', 'Đã xử lý (hoàn thành)'),
    ('HUY', 'Đã hủy/từ chối'),
]

SECURITY_LEVELS = [
    ('BT', 'Thường'),
    ('MM', 'Mật'),
    ('TT', 'Tối mật'),
    ('TTT', 'Tuyệt mật'),
]

USAGE_PURPOSES = [
    ('GD', 'Giao dịch'),
    ('PTDL', 'Phân tích dữ liệu'),
    ('QLRR', 'Quản lý rủi ro'),
    ('KT', 'Kế toán'),
]

COMPUTER_NETWORKS = [
    ('intranet', 'Mạng nội bộ'),
    ('internet', 'Internet'),
    ('dmz', 'DMZ (Vùng phi quân sự)'),
    ('vpn', 'VPN (Mạng riêng ảo)'),
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'current_user.CurrentUserMiddleware',
]

ROOT_URLCONF = 'qlkt.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'qlkt.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'qlkt',
#         'USER': 'red',
#         'PASSWORD': 'red',
#         'HOST': 'localhost',
#         'PORT': '5432'
#     }
# }

LANGUAGE_CODE = 'vi'
from django.utils.translation import gettext, gettext_lazy as _
LANGUAGES = [
    ('en', _('English')),
    ('vi', _('Vietnamese')),
]

#LANGUAGE_CODE = 'en-us'

import os
LOCALE_PATHS = [os.path.join(BASE_DIR, 'locale')]

TIME_ZONE = 'Asia/Ho_Chi_Minh'
#TIME_ZONE = 'UTC'
USE_I18N = True

USE_L10N = True

USE_TZ = True


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
# Các thư mục chứa tệp tĩnh mà Django sẽ tìm kiếm
STATICFILES_DIRS = [
    BASE_DIR / "static",  # Thư mục static trong thư mục gốc của dự án
]
import os

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
