# Generated by Django 5.1 on 2025-05-11 16:12

import current_user
import datetime
import django.db.models.deletion
import smart_selects.db_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('equipments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseOperation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='MS')),
                ('received_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Ngày tiếp nhận yêu cầu')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.department', verbose_name='Đơn vị/Phòng ban')),
                ('equipments', models.ManyToManyField(blank=True, related_name='equipments', to='equipments.equipment', verbose_name='Trang bị')),
                ('request_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.requirementtype', verbose_name='Loại yêu cầu')),
                ('status', models.ForeignKey(default='TN', on_delete=django.db.models.deletion.PROTECT, to='common.handlestatustype', verbose_name='Trạng thái')),
            ],
            options={
                'verbose_name': 'Xử lý kỹ thuật',
                'verbose_name_plural': 'Xử lý kỹ thuật',
                'db_table': 'base_operation',
            },
        ),
        migrations.CreateModel(
            name='EquipmentDeployment',
            fields=[
                ('baseoperation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operations.baseoperation')),
                ('borrow_date', models.DateField(default=datetime.datetime.now, verbose_name='Ngày mượn')),
                ('pay_date', models.DateField(blank=True, null=True, verbose_name='Ngày trả')),
                ('hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Số giờ sử dụng')),
                ('st', models.BooleanField(default=False, verbose_name='Đã trả trang bị')),
                ('borrower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='borrow', to='common.staff', verbose_name='Người mượn thiết bị')),
                ('lender', models.ForeignKey(default=current_user.get_current_user, on_delete=django.db.models.deletion.PROTECT, related_name='lend', to=settings.AUTH_USER_MODEL, verbose_name='Người cho mượn')),
                ('payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pay', to='common.staff', verbose_name='Người trả')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receive', to=settings.AUTH_USER_MODEL, verbose_name='Người nhận trả')),
            ],
            options={
                'verbose_name': 'Điều động',
                'verbose_name_plural': 'Điều động',
                'db_table': 'equipment_deployments',
            },
            bases=('operations.baseoperation',),
        ),
        migrations.CreateModel(
            name='EquipmentHandover',
            fields=[
                ('baseoperation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operations.baseoperation')),
                ('handover_date', models.DateTimeField(verbose_name='Thời gian bàn giao')),
                ('from_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers_from', to='common.staff', verbose_name='Bên giao')),
                ('to_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers_to', to='common.staff', verbose_name='Bên nhận')),
            ],
            options={
                'verbose_name': 'Bàn giao trang bị',
                'verbose_name_plural': 'Bàn giao',
                'db_table': 'equipment_handovers',
            },
            bases=('operations.baseoperation',),
        ),
        migrations.CreateModel(
            name='EquipmentLiquidation',
            fields=[
                ('baseoperation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operations.baseoperation')),
                ('liquidation_date', models.DateField(verbose_name='Ngày thanh lý')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_liquidations', to='common.staff', verbose_name='Người phê duyệt')),
            ],
            options={
                'verbose_name': 'Thanh lý trang bị',
                'verbose_name_plural': 'Thanh lý',
                'db_table': 'equipment_liquidations',
            },
            bases=('operations.baseoperation',),
        ),
        migrations.CreateModel(
            name='EquipmentRepair',
            fields=[
                ('baseoperation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operations.baseoperation')),
                ('repair_date', models.DateField(verbose_name='Thời gian sửa chữa')),
                ('repair_content', models.TextField(blank=True, null=True, verbose_name='Nội dung xử lý')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày trả')),
                ('department_approver', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='department', chained_model_field='department', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='repair_approver', to='common.staff', verbose_name='Chỉ huy phòng ban phê duyệt')),
                ('error', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='error', to='common.errortype', verbose_name='Hiện tượng hỏng hóc')),
                ('repair_staff', models.ManyToManyField(blank=True, related_name='repair_staff', to=settings.AUTH_USER_MODEL, verbose_name='Cán bộ tiếp nhận & xử lý')),
                ('requester', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='department', chained_model_field='department', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='repair_requester', to='common.staff', verbose_name='Cán bộ yêu cầu xử lý')),
                ('result_deliverer', models.ForeignKey(default=current_user.get_current_user, on_delete=django.db.models.deletion.PROTECT, related_name='result_deliverer', to=settings.AUTH_USER_MODEL, verbose_name='Cán bộ trả kết quả xử lý')),
                ('result_receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='result_receiver', to='common.staff', verbose_name='CB nhận kết quả xử lý')),
            ],
            options={
                'verbose_name': 'Sửa chữa trang bị',
                'verbose_name_plural': 'Sửa chữa',
                'db_table': 'equipment_repairs',
            },
            bases=('operations.baseoperation',),
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('baseoperation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operations.baseoperation')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày trả')),
                ('request_content', models.TextField(blank=True, null=True, verbose_name='Nội dung yêu cầu xử lý')),
                ('quantity', models.PositiveIntegerField(verbose_name='Số lượng')),
                ('processing_content', models.TextField(blank=True, null=True, verbose_name='Nội dung xử lý')),
                ('has_material_debt', models.BooleanField(default=False, verbose_name='Nợ vật tư')),
                ('department_approver', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='department', chained_model_field='department', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ktdb_approver', to='common.staff', verbose_name='Chỉ huy phòng ban phê duyệt')),
                ('processing_staff', models.ManyToManyField(blank=True, related_name='handler', to=settings.AUTH_USER_MODEL, verbose_name='Cán bộ xử lý')),
                ('receiving_officer', models.ForeignKey(default=current_user.get_current_user, on_delete=django.db.models.deletion.PROTECT, related_name='receiver', to=settings.AUTH_USER_MODEL, verbose_name='Cán bộ tiếp nhận')),
                ('requester', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='department', chained_model_field='department', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ktdb_presenter', to='common.staff', verbose_name='Cán bộ yêu cầu xử lý')),
                ('result_deliverer', models.ForeignKey(default=current_user.get_current_user, on_delete=django.db.models.deletion.PROTECT, related_name='giver', to=settings.AUTH_USER_MODEL, verbose_name='Cán bộ trả kết quả xử lý')),
                ('result_receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handover', to='common.staff', verbose_name='CB nhận kết quả xử lý')),
            ],
            options={
                'verbose_name': 'Yêu cầu xử lý',
                'verbose_name_plural': 'Yêu cầu xử lý',
                'db_table': 'requirement',
            },
            bases=('operations.baseoperation',),
        ),
        migrations.CreateModel(
            name='NetworkMaintenanceLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Ms')),
                ('network', models.CharField(blank=True, choices=[('intranet', 'Mạng nội bộ'), ('internet', 'Internet'), ('dmz', 'DMZ (Vùng phi quân sự)'), ('vpn', 'VPN (Mạng riêng ảo)')], max_length=10, null=True, verbose_name='Mạng máy tính')),
                ('date', models.DateField(verbose_name='Ngày bảo trì')),
                ('description', models.TextField(verbose_name='Nội dung bảo trì')),
                ('performed_by', models.ManyToManyField(blank=True, related_name='maintenance_logs', to='common.staff', verbose_name='Nhân viên bảo trì')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operations.requirement', verbose_name='Yêu cầu xử lý')),
            ],
            options={
                'verbose_name': 'Bảo trì mạng',
                'verbose_name_plural': 'Kiểm tra, bảo trì mạng',
                'db_table': 'network_maintenance_logs',
            },
        ),
    ]
